# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('none', '')], default='', max_length=6),
        ),
    ]
