# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pettifyapp', '0002_auto_20160226_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Separate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('none', ''), ('cat', 'Cat'), ('dog', 'Dog'), ('fish', 'Fish'), ('hamster', 'Hamster'), ('lizard', 'Lizard'), ('snake', 'Snake')], default='', max_length=100)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pettifyapp.Separate'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('none', ''), ('male', 'Male'), ('female', 'Female')], default='', max_length=6),
        ),
    ]
