# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettifyapp', '0002_auto_20160226_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('none', ''), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=6),
        ),
    ]
