# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettifyapp', '0003_auto_20160226_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='Separate',
        ),
    ]
